[package]
name = "arkham_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.2", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_derive = "1.0.196"
serde_json = "1.0.114"
tokio = {version = "1.36.0", features = ["full"]}
